public class FindTheDifferenceSolution {
    public char FindTheDifference(string s, string t) {
        for(int i = 0; i < t.Length; i++){
            if(s.IndexOf(t[i])==-1 || s.Replace(t[i].ToString(),"").Length == t.Replace(t[i].ToString(),"").Length) return t[i];
        }
        return '/';
    }
}

/*
 * You are given two strings s and t.
   
   String t is generated by random shuffling string s and then add one more letter at a random position.
   
   Return the letter that was added to t.
   
 */